apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vibe-check-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/vibe-check-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: FRONTEND_URL
          value: "https://vibe-check-frontend-PROJECT_ID.a.run.app"
        - name: REDIS_URL
          value: "redis://redis-server:6379"
        - name: ZAP_API_URL
          value: "http://zap-scanner:8080"
        - name: OSV_API_URL
          value: "https://api.osv.dev"
        - name: TRIVY_API_URL
          value: "http://trivy-scanner:8080"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
