export const DEFAULT_POLICIES = [
  {
    id: 'policy-default-safe',
    name: 'Safe Default',
    mode: 'passive',
    maxReqPerMin: 120,
    spiderDepth: 5,
    allowedTools: ['ZAP', 'OSV'],
    description: 'Comprehensive security scan with moderate speed. Best for production applications. Non-intrusive passive scanning only.',
    exclusions: [],
  },
  {
    id: 'policy-quick-scan',
    name: 'Quick Scan',
    mode: 'passive',
    maxReqPerMin: 200,
    spiderDepth: 1,
    allowedTools: ['ZAP', 'OSV'],
    description: 'Faster scan with basic coverage. Good for development and testing. Non-intrusive passive scanning only.',
    exclusions: [],
  },
  {
    id: 'policy-comprehensive',
    name: 'Comprehensive Scan',
    mode: 'passive',
    maxReqPerMin: 80,
    spiderDepth: 10,
    allowedTools: ['ZAP', 'OSV'],
    description: 'Thorough security analysis with deep crawling. Recommended for critical applications. Non-intrusive passive scanning only.',
    exclusions: [],
  },
  {
    id: 'policy-dependency-only',
    name: 'Dependency Check',
    mode: 'passive',
    maxReqPerMin: 100,
    spiderDepth: 1,
    allowedTools: ['OSV'],
    description: 'Quick dependency vulnerability check only. Fastest option for package scanning.',
    exclusions: [],
  },
  {
    id: 'policy-passive-only',
    name: 'Passive Scan (Non-Intrusive)',
    mode: 'passive',
    maxReqPerMin: 150,
    spiderDepth: 5,
    allowedTools: ['ZAP', 'OSV'],
    description: 'Non-intrusive scan using spider and passive scanning only. Safe for production environments. No active vulnerability testing.',
    exclusions: [],
  },
] as const;

export const DEFAULT_ADMIN_SETTINGS = {
  dataRetentionDays: 90,
  scanConcurrencyCap: 5,
  defaultRateLimit: 100,
};
